### ISSUE TITLE
Melhorar README.md

### ISSUE THREAD

**Issue by eduhique** [lucasvictor3/SirDraw#1]
Ao ler a descrição apresentada eu consigo entender qual a finalidade geral da aplicação, mas não como ela vai funcionar. Como vai funcionar o cadastro de sorteios? Vai ser apenas um sorteio por vez? Quem pode criar sorteios? Aliás quem cria os sorteios?
Enfim uma descrição de readme de algo como o que a disciplina propõe deve ter uma descrição suficiente para que outras pessoas (colegas, professor, usuários do git, dentre outros) possam ler e conseguir entender a ideia completa e não parte dela.

**Comment by lucasvictor3** [comment]
Adicionado mais alguns detalhes
