### ISSUE TITLE
Parâmetros faltantes em interface

### ISSUE THREAD

**Issue by eduhique** [lucasvictor3/SirDraw#10]
Os parâmetros usados por essa atribuição não corresponde ao exigidos pela interface.
https://github.com/lucasvictor3/SirDraw/blob/787af1044da6b13ffd97df4fff6d19b089eda148/backend/src/modules/sweepStakes/SweepStakesService.ts#L31-L38

A interface:
https://github.com/lucasvictor3/SirDraw/blob/787af1044da6b13ffd97df4fff6d19b089eda148/backend/src/modules/sweepStakes/SweepStakesService.ts#L3-L12

Para roda tive que corrigir essa falta de atribuição.

**Comment by lucasvictor3** [comment]
Valeu, atualizei aq.. lembro que corrigi local mas não subi isso pro git o/
