### ISSUE TITLE
Rota para API não correspondente

### ISSUE THREAD

**Issue by eduhique** [lucasvictor3/SirDraw#11]
Quando se usa uma API em localhost não é muito bom atribuir um ip da sua rede privada, pois muito provavelmente não será a mesa em outras redes privadas. No caso abaixo, não funcionou no meu sistema, pois meu ip é outro:
https://github.com/lucasvictor3/SirDraw/blob/787af1044da6b13ffd97df4fff6d19b089eda148/frontend/sirdraw/src/components/util/sweepStakeHandler.ts#L16
Nesses caso de uso de API locais é correto utilizar: `http://localhost/`

**Comment by lucasvictor3** [comment]
Sim, só utilizei dessa maneira porque já tive problemas com isso, mas como a intenção é hospedar o backend futuramente, isso iria ser substituido de qualquer maneira. De qualquer forma, já atualizei a rota
