### ISSUE TITLE
Criar um único arquivo representando a interface Sweepstake

### ISSUE THREAD

**Issue by LucasCBrasil** [lucasvictor3/SirDraw#14]
Vi que foi declarada praticamente a mesma interface de Sweepstake tanto no frontend(sweepStakeHandler.ts) como no backend(SweepStakeService.ts) - apenas um campo a mais de diferença em uma delas. Sugiro que, se possível, crie um arquivo separado para essa interface e importe o mesmo nos locais em que a mesma será usada.

**Comment by lucasvictor3** [comment]
Valeu pela dica, atualmente sincronizei as interfaces mas irei colocar em um unico arquivo em breve.
