### ISSUE TITLE
Dica: Evite usar estilos dentro do html

### ISSUE THREAD

**Issue by eduhique** [lucasvictor3/SirDraw#2]
Seguir boas práticas é essencial para um bom programador, pois na grande maioria das vezes ou você não programa apenas para você ou está programando em grupo (Raramente programa só). Então seguir boas praticas é essencial e nesse contexto é não legal incluir CSS no HTML, como no exemplo abaixo, pois dificulta a depuração e além disso existe um forma mais coesa de se fazer isso. Enfim as principais boas práticas que busco seguir são:

- Manter uma indentação adequada;
- Usar nomes adequados para as variáveis (pois na maioria das vezes outras pessoas precisarão entender seu código);
- Documentar bem;
- Manter a coesão;
- Fazer tratamento de erros;

https://github.com/lucasvictor3/SirDraw/blob/b22e50417a82c496a7470244c3427ffa0b39847c/index.html#L4-L22

Por fim, quando se trata de web evito sempre misturar HTML, JS e CSS com exceção quando isso for recurso da linguagem. Manter uma boa organização, agrupamento e ordem é muito importante. No caso da ordem, se deve mais ao CSS, sempre que puder siga a ordem das tags HTML. Por fim, busque não sobrescrever regra, melhor comentário muitas vez é um código limpo e auto explicativo e toda regra tem sua exceção, mas não abuse!

Existem muito mais coisas, aliás isso tá sempre mudando, mas ja falei demais hehehe

**Comment by lucasvictor3** [comment]
Valeu pela dica, alguns style eu deixei nos componentes quando eles fazem parte da interação com alguma logica, mas boa parte do CSS já passei para um arquivo .less
