### ISSUE TITLE
Adicionar instruções de como executar o projeto localmente no README.md

### ISSUE THREAD

**Issue by paulojuniore** [lucasvictor3/SirDraw#4]
Seria interessante além do README ter uma descrição mais detalhada sobre o projeto e suas funcionalidades, também ter instruções de como executar ambas as partes, tanto o backend, como o frontend. Para ficar mais organizado você poderia até criar um README na pasta backend e colocar especificamente como executar o backend, e na raiz do repositório como executar o frontend.

**Comment by lucasvictor3** [comment]
Como é simples a inicialização, deixei apenas no README.md principal

**Comment by paulojuniore** [comment]
Antes do "yarn start" você não deveria entrar em alguma das pastas (backend ou frontend) e instalar as dependências com o "npm install"? Creio que você poderia ser um pouco mais claro.

**Comment by lucasvictor3** [comment]
Eu tava pra colocar mas devo ter me distraido com outra coisa me esqueci, adicionei mais instruções, mas de qualquer forma, em breve, prefiro deixar isso já pronto num Makefile
