### ISSUE TITLE
Seguir Boas práticas para desenvolvimento de API REST

### ISSUE THREAD

**Issue by eduhique** [lucasvictor3/SirDraw#5]
Ao desenvolver uma API é muito importante seguir boas praticas de desenvolciemento. Se não conhece ou tem duvidas uma pesquisa rápida como, por exemplo, pesquisar no google `Boas práticas API Rest` pode sanar todas as dúvidas.

**Comment by lucasvictor3** [comment]
Você poderia identificar o que mais precisa mudar ou foge do padrão? essa issue ficou muito vaga. Um detalhe é que muita coisa ainda vai passar por refatoração nas proximas entregas então preciso saber os pontos que realmente nao cobri.

**Comment by eduhique** [comment]
Um exemplo de boa prática é padronizar as rotas. Não consegui entender se a rota post `/draw` é uma ação ou um objeto, pois não vi nenhum padrão de projeto (MVC é o mais comum) sendo seguido...

**Comment by lucasvictor3** [comment]
Draw é um sorteio, dessa forma, seguindo o padrão web API, o post já indica q é um registro de um sorteio, nesse caso, um objeto. Nas próximas entregas manterei esse padrão, obrigado pela sugestão.
