### ISSUE TITLE
Adicionar tratamento de erros em body de requisições

### ISSUE THREAD

**Issue by FMota0** [lucasvictor3/SirDraw#7]
Por exemplo tratar se o tipo de totalTickets
https://github.com/lucasvictor3/SirDraw/blob/1f16f40c773e65273ff4c6e8df8ef4fcac9aba2c/backend/src/modules/tickets/TicketsController.ts#L8

**Comment by lucasvictor3** [comment]
strings e numbers foram tratados no controller e arrays dentro do service mesmo.
