### ISSUE TITLE
Function Components

### ISSUE THREAD

**Issue by AramisAraujo** [lucasvictor3/SirDraw#9]
Olá, notei que para vários componentes você os declarou com uma sintaxe que pode se tornar muito verborrágica.

É possível declarar componentes de uma forma que acredito ser mais simples, dá uma olhada no link abaixo :) .

[Discussão aqui](https://stackoverflow.com/questions/53935996/whats-the-difference-between-a-react-functioncomponent-and-a-plain-js-function/53936088)

**Comment by lucasvictor3** [comment]
Entendi, realmente deixa o código mais _clean_, já comecei a subir algumas modificações sem tantas definições de tipos. Valeu pela dica o/
